version: '3.3'

services:
  phpipam-web:
    image: phpipam/phpipam-www
#    ports:
#      - "80:80"
    environment:
      - TZ=Europe/London
      - IPAM_DATABASE_HOST=phpipam-mariadb
      # - IPAM_DATABASE_PASS=my_secret_phpipam_pass
      - IPAM_DATABASE_WEBHOST=%
    restart: unless-stopped
    volumes:
      - phpipam-logo:/phpipam/css/images/logo
    configs:
      - source: configphp
        target: /phpipam/config.php
    depends_on:
      - phpipam-mariadb

  phpipam-cron:
    image: phpipam/phpipam-cron:latest
    environment:
      - TZ=Europe/London
      - IPAM_DATABASE_HOST=phpipam-mariadb
      # - IPAM_DATABASE_PASS=my_secret_phpipam_pass
      - SCAN_INTERVAL=1h
    restart: unless-stopped
    depends_on:
      - phpipam-mariadb

  phpipam-mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=997406ea-e300-4200-b0b8-add6958bcfca
    restart: unless-stopped
    volumes:
      - phpipam-db-data:/var/lib/mysql

  openldap:
    image: bitnami/openldap:latest
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=04b15974-01d3-4def-9e9d-c60413566235
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,7e097ff3-a7e0-4913-ae9e-b17ae7cb4f43
      - LDAP_ORGANISATION=example-org
      - LDAP_DOMAIN=example.org
      - LDAP_CONFIG_PASSWORD=config
      - LDAP_RFC2307BIS_SCHEMA=true
      - LDAP_REMOVE_CONFIG_AFTER_SETUP=true
      - LDAP_TLS_VERIFY_CLIENT=never
      - LDAP_CONFIG_ADMIN_ENABLED=yes
      - LDAP_CONFIG_ADMIN_USERNAME=configadmin
      - LDAP_CONFIG_ADMIN_PASSWORD=0c601e86-9404-4dbe-a1e6-db5607e9e330
      - LDAP_USER_DC=people


    volumes:
      - 'openldap_data:/bitnami/openldap'

  ldapsetup:
    image: debian:latest
    depends_on:
      - openldap
    restart: "no"

    entrypoint: ["sh", "-c", 'apt-get update && apt-get -y install ldap-utils && ldapmodify -v -h openldap -p 1389 -D "cn=configadmin,cn=config" -w 0c601e86-9404-4dbe-a1e6-db5607e9e330 -f /customldifs/privileges.ldif && ldapmodify -v -h openldap -p 1389 -D "uid=admin,dc=example,dc=org" -w 04b15974-01d3-4def-9e9d-c60413566235 -f /customldifs/bootstrapusers.ldif']


    volumes:
      - './ldifs:/customldifs'

  mariadbsetup:
    image: debian:latest
    depends_on:
      - phpipam-mariadb
      - phpipam-web
      - phpipam-cron
      - ldapsetup
    restart: "no"

    # login password to web interface, username admin: 74da46d1-ac7a-49af-b5f7-9bda12d62b0f

    entrypoint: ["sh", "-c", "apt-get update && apt-get -y install mariadb-client && mysql -h phpipam-mariadb -u root -p997406ea-e300-4200-b0b8-add6958bcfca mysql < /database/bootstrap.sql && mysql -h phpipam-mariadb -u root -p997406ea-e300-4200-b0b8-add6958bcfca phpipam < /database/phpipam.sql && mysql -h phpipam-mariadb -u root -p997406ea-e300-4200-b0b8-add6958bcfca phpipam < /database/privileges.sql"]


    volumes:
      - './database:/database'

  reverseproxy:
    depends_on:
      - phpipam-web
    build:
      context: .
      dockerfile: nginx/nginx.Dockerfile
    ports:
      - "443:443"
      - "80:80"
    restart: always

volumes:
  phpipam-db-data:
  phpipam-logo:
  openldap_data:

configs:
  configphp:
    file: modified_files/phpipam/config.php
